<?php

namespace Container51bben1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePortfolioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PorfolioClients\Command\GeneratePortfolio' shared autowired service.
     *
     * @return \App\PorfolioClients\Command\GeneratePortfolio
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/PorfolioClients/Command/GeneratePortfolio.php';
        include_once \dirname(__DIR__, 4).'/src/PorfolioClients/Application/CustomerCsvCreator.php';
        include_once \dirname(__DIR__, 4).'/src/PorfolioClients/Domain/Service/GetCustomers.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Adapter/GuzzleAdapter.php';
        include_once \dirname(__DIR__, 4).'/src/PorfolioClients/Domain/CustomerRepository.php';
        include_once \dirname(__DIR__, 4).'/src/PorfolioClients/Infrastructure/CustomerApiRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';
        include_once \dirname(__DIR__, 4).'/src/PorfolioClients/Domain/Service/XmlConverter.php';

        $container->privates['App\\PorfolioClients\\Command\\GeneratePortfolio'] = $instance = new \App\PorfolioClients\Command\GeneratePortfolio(new \App\PorfolioClients\Application\CustomerCsvCreator(new \App\PorfolioClients\Domain\Service\GetCustomers(new \App\PorfolioClients\Infrastructure\CustomerApiRepository(new \GuzzleHttp\Client())), new \App\PorfolioClients\Domain\Service\XmlConverter()));

        $instance->setName('app:generate-portfolio');

        return $instance;
    }
}
